/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 97e20379-9c78-4dcd-a3af-85fc05d6e326

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the proposition: For interior points, the evaluation functional is continuous with respect to the Sobolev norm, extends uniquely to the Hilbert space, and has a closed kernel.

The formalization assumes the Sobolev inequality on the circle as a hypothesis `h_sobolev`.
It defines:
- `eval_continuous`: The evaluation functional on polynomials as a continuous linear map.
- `extended_eval`: The extension of the evaluation functional to the Hilbert space H.
It proves:
- `evaluation_bounded`: The evaluation functional is bounded.
- `extension_unique`: The extension is unique.
- `kernel_closed`: The kernel of the extended functional is closed.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Fórmula Integral de Cauchy para polinomios.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

lemma polynomial_cauchy_formula (R : ℝ) (hR : 0 < R) (c : ℂ) (hc : ‖c‖ < R) (p : Polynomial ℂ) :
    p.eval c = (1 / (2 * Real.pi * I)) * ∮ z in C(0, R), (z - c)⁻¹ * p.eval z := by
  have := @Complex.circleIntegral_sub_inv_smul_of_differentiable_on_off_countable;
  specialize @this ℂ _ _ _ R 0 c ( fun z => p.eval z ) ∅ ; norm_num at this;
  rw [ this hc ( p.continuous.continuousOn ) fun z hz => p.differentiableAt ] ; ring ; norm_num [ Real.pi_ne_zero ];
  norm_num [ mul_assoc, mul_comm, mul_left_comm, Real.pi_ne_zero, Complex.ext_iff ]

/-
Acotación del valor del polinomio en un punto interior por la norma L2 en la frontera.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

lemma evaluation_le_integral_norm_sq (R : ℝ) (hR : 0 < R) (c : ℂ) (hc : ‖c‖ < R) (p : Polynomial ℂ) :
    ∃ K, 0 < K ∧ ‖p.eval c‖^2 ≤ K * ∫ t in (0)..2*Real.pi, ‖p.eval (R * cexp (I * t))‖^2 * R := by
  by_cases h : ∫ t in ( 0 : ℝ )..2 * Real.pi, ‖p.eval ( R * Complex.exp ( Complex.I * t ) )‖ ^ 2 * R = 0;
  · -- If the integral is zero, then $p(z)$ is zero almost everywhere on the circle $|z|=R$, hence $p(z)$ is the zero polynomial.
    have h_zero_poly : p = 0 := by
      rw [ intervalIntegral.integral_of_le Real.two_pi_pos.le ] at h;
      rw [ MeasureTheory.integral_eq_zero_iff_of_nonneg ( fun _ => by positivity ) ] at h;
      · rw [ Filter.EventuallyEq, MeasureTheory.ae_restrict_iff' ] at h;
        · rw [ MeasureTheory.ae_iff ] at h;
          contrapose! h;
          -- Since $p$ is a non-zero polynomial, the set of roots of $p$ is finite.
          have h_roots_finite : Set.Finite {z : ℂ | p.eval z = 0} := by
            exact p.roots.toFinset.finite_toSet.subset fun x hx => by aesop;
          -- Since $p$ is a non-zero polynomial, the set of roots of $p$ is finite, and thus the set of $t$ such that $p(R e^{it}) = 0$ is also finite.
          have h_roots_finite_t : Set.Finite {t : ℝ | t ∈ Set.Ioc 0 (2 * Real.pi) ∧ p.eval (R * Complex.exp (Complex.I * t)) = 0} := by
            have h_roots_finite_t : Set.Finite (Set.image (fun t : ℝ => R * Complex.exp (Complex.I * t)) {t : ℝ | t ∈ Set.Ioc 0 (2 * Real.pi) ∧ p.eval (R * Complex.exp (Complex.I * t)) = 0}) := by
              exact h_roots_finite.subset <| Set.image_subset_iff.mpr fun x hx => hx.2;
            convert h_roots_finite_t.of_finite_image _;
            intros t ht t' ht' h_eq; simp_all +decide [ Complex.exp_eq_exp_iff_exists_int, mul_comm Complex.I ];
            rcases h_eq with ( ⟨ n, hn ⟩ | rfl ) <;> norm_num [ Complex.ext_iff ] at *;
            rcases n with ⟨ _ | n ⟩ <;> norm_num at * <;> nlinarith [ Real.pi_pos ];
          simp_all +decide [ ne_of_gt hR ];
          rw [ show { a : ℝ | ( 0 < a ∧ a ≤ 2 * Real.pi ) ∧ ¬Polynomial.eval ( R * Complex.exp ( Complex.I * a ) ) p = 0 } = Set.Ioc 0 ( 2 * Real.pi ) \ { t : ℝ | ( 0 < t ∧ t ≤ 2 * Real.pi ) ∧ Polynomial.eval ( R * Complex.exp ( Complex.I * t ) ) p = 0 } by ext; aesop, MeasureTheory.measure_diff_null ] <;> norm_num [ Real.pi_pos ];
          exact h_roots_finite_t.measure_zero MeasureTheory.MeasureSpace.volume;
        · norm_num;
      · exact Continuous.integrableOn_Ioc ( by exact Continuous.mul ( Continuous.pow ( by exact p.continuous.norm.comp <| by continuity ) _ ) continuous_const );
    aesop;
  · exact ⟨ ( ‖p.eval c‖ ^ 2 + 1 ) / ( ∫ t in ( 0 : ℝ )..2 * Real.pi, ‖p.eval ( R * Complex.exp ( Complex.I * t ) )‖ ^ 2 * R ), div_pos ( by positivity ) ( lt_of_le_of_ne ( by exact intervalIntegral.integral_nonneg ( by positivity ) fun _ _ => mul_nonneg ( sq_nonneg _ ) ( by positivity ) ) ( Ne.symm h ) ), by rw [ div_mul_cancel₀ _ h ] ; linarith ⟩

/-
Acotación uniforme del valor del polinomio.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

lemma evaluation_le_integral_norm_sq_uniform (R : ℝ) (hR : 0 < R) (c : ℂ) (hc : ‖c‖ < R) :
    ∃ K > 0, ∀ p : Polynomial ℂ, ‖p.eval c‖^2 ≤ K * ∫ t in (0)..2*Real.pi, ‖p.eval (R * cexp (I * t))‖^2 * R := by
  -- By the Cauchy-Schwarz inequality, we have that for any polynomial $p$,
  -- $|p(c)| \leq \frac{1}{2\pi} \int_0^{2\pi} \frac{|p(R e^{it})|}{|R e^{it} - c|} R dt$.
  have h_cauchy_schwarz : ∀ p : Polynomial ℂ, ‖p.eval c‖ ≤ (1 / (2 * Real.pi)) * ∫ t in (0)..2 * Real.pi, ‖p.eval (R * Complex.exp (Complex.I * t))‖ * R / ‖R * Complex.exp (Complex.I * t) - c‖ := by
    -- Apply the Cauchy-Schwarz inequality to the integral expression for $p(c)$.
    intro p
    have h_cauchy_schwarz_step : ‖p.eval c‖ ≤ (1 / (2 * Real.pi)) * ∫ t in (0)..2 * Real.pi, ‖(R * Complex.exp (Complex.I * t) - c)⁻¹ * p.eval (R * Complex.exp (Complex.I * t)) * R * Complex.exp (Complex.I * t)‖ := by
      have h_cauchy_schwarz_step : p.eval c = (1 / (2 * Real.pi * Complex.I)) * ∫ t in (0)..2 * Real.pi, (R * Complex.exp (Complex.I * t) - c)⁻¹ * p.eval (R * Complex.exp (Complex.I * t)) * R * Complex.exp (Complex.I * t) * Complex.I := by
        have := @polynomial_cauchy_formula R hR c hc p;
        rw [ this, circleIntegral ];
        norm_num [ mul_assoc, mul_comm, mul_left_comm, circleMap ];
      simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, intervalIntegral.integral_comp_mul_right, Real.pi_pos.ne.symm, Complex.exp_ne_zero ];
      gcongr <;> norm_num [ abs_of_pos, Real.pi_pos ];
      convert intervalIntegral.norm_integral_le_integral_norm _ using 2 ; norm_num [ Complex.norm_exp ];
      positivity;
    convert h_cauchy_schwarz_step using 3 ; norm_num [ Complex.norm_exp, div_eq_inv_mul, mul_assoc, mul_comm, mul_left_comm ];
    norm_num [ abs_of_pos hR ];
  -- Applying the Cauchy-Schwarz inequality to the integral, we get:
  have h_cauchy_schwarz_integral : ∀ p : Polynomial ℂ, (∫ t in (0)..2 * Real.pi, ‖p.eval (R * Complex.exp (Complex.I * t))‖ * R / ‖R * Complex.exp (Complex.I * t) - c‖) ^ 2 ≤ (∫ t in (0)..2 * Real.pi, ‖p.eval (R * Complex.exp (Complex.I * t))‖ ^ 2 * R) * (∫ t in (0)..2 * Real.pi, R / ‖R * Complex.exp (Complex.I * t) - c‖ ^ 2) := by
    intros p
    have h_cauchy_schwarz_integral : (∫ t in (0)..2 * Real.pi, ‖p.eval (R * Complex.exp (Complex.I * t))‖ * R / ‖R * Complex.exp (Complex.I * t) - c‖) ^ 2 ≤ (∫ t in (0)..2 * Real.pi, ‖p.eval (R * Complex.exp (Complex.I * t))‖ ^ 2 * R) * (∫ t in (0)..2 * Real.pi, R / ‖R * Complex.exp (Complex.I * t) - c‖ ^ 2) := by
      have h_inner_product : ∀ f g : ℝ → ℝ, ContinuousOn f (Set.Icc 0 (2 * Real.pi)) → ContinuousOn g (Set.Icc 0 (2 * Real.pi)) → (∫ t in (0)..2 * Real.pi, f t * g t) ^ 2 ≤ (∫ t in (0)..2 * Real.pi, f t ^ 2) * (∫ t in (0)..2 * Real.pi, g t ^ 2) := by
        intros f g hf hg
        have h_inner_product : (∫ t in (0)..2 * Real.pi, (f t - (∫ u in (0)..2 * Real.pi, f u * g u) / (∫ u in (0)..2 * Real.pi, g u ^ 2) * g t) ^ 2) ≥ 0 := by
          exact intervalIntegral.integral_nonneg ( by positivity ) fun x hx => sq_nonneg _;
        by_cases h : ∫ u in ( 0 : ℝ )..2 * Real.pi, g u ^ 2 = 0 <;> simp_all +decide [ sub_sq, mul_assoc, mul_comm, mul_left_comm, div_eq_inv_mul ];
        · rw [ intervalIntegral.integral_of_le ( by positivity ) ] at *;
          rw [ MeasureTheory.integral_eq_zero_iff_of_nonneg ( fun x => sq_nonneg _ ) ] at h;
          · exact MeasureTheory.integral_eq_zero_of_ae ( h.mono fun x hx => by aesop );
          · exact ContinuousOn.integrableOn_Icc ( hg.pow 2 ) |> fun h => h.mono_set ( Set.Ioc_subset_Icc_self );
        · rw [ intervalIntegral.integral_add, intervalIntegral.integral_sub ] at h_inner_product <;> norm_num [ mul_pow, ← mul_assoc, ← sq ] at *;
          · nlinarith [ inv_mul_cancel_left₀ h ( ∫ u in ( 0 : ℝ )..Real.pi * 2, f u * g u ), inv_mul_cancel₀ h, inv_mul_cancel₀ ( pow_ne_zero 2 h ), show 0 ≤ ∫ u in ( 0 : ℝ )..Real.pi * 2, f u ^ 2 from intervalIntegral.integral_nonneg ( by positivity ) fun _ _ => sq_nonneg _, show 0 ≤ ∫ u in ( 0 : ℝ )..Real.pi * 2, g u ^ 2 from intervalIntegral.integral_nonneg ( by positivity ) fun _ _ => sq_nonneg _ ];
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            simpa only [ Set.uIcc_of_le ( by positivity : 0 ≤ Real.pi * 2 ) ] using hf.pow 2;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            simpa only [ Set.uIcc_of_le ( by positivity : 0 ≤ Real.pi * 2 ) ] using ContinuousOn.mul ( ContinuousOn.mul ( ContinuousOn.mul ( ContinuousOn.mul hf hg ) continuousOn_const ) continuousOn_const ) continuousOn_const;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            simpa only [ Set.uIcc_of_le ( by positivity : 0 ≤ Real.pi * 2 ) ] using ContinuousOn.sub ( hf.pow 2 ) ( ContinuousOn.mul ( ContinuousOn.mul ( ContinuousOn.mul ( hf.mul hg ) continuousOn_const ) continuousOn_const ) continuousOn_const );
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            simpa only [ Set.uIcc_of_le ( by positivity : 0 ≤ Real.pi * 2 ) ] using ContinuousOn.mul ( ContinuousOn.mul ( hg.pow 2 ) ( continuousOn_const ) ) ( continuousOn_const )
      convert h_inner_product ( fun t => ‖p.eval ( R * Complex.exp ( Complex.I * t ) )‖ * Real.sqrt R ) ( fun t => Real.sqrt R / ‖R * Complex.exp ( Complex.I * t ) - c‖ ) _ _ using 3 <;> norm_num [ div_eq_mul_inv, mul_pow, mul_assoc, mul_comm, mul_left_comm, Real.sq_sqrt <| le_of_lt hR ];
      · exact funext fun x => by rw [ Real.mul_self_sqrt hR.le ] ; ring;
      · fun_prop;
      · refine' ContinuousOn.mul ( ContinuousOn.inv₀ _ _ ) continuousOn_const;
        · fun_prop;
        · intro x hx; intro H; simp_all +decide [ Complex.exp_ne_zero, sub_eq_iff_eq_add ];
          exact hc.not_le ( by rw [ ← H ] ; norm_num [ Complex.norm_exp, abs_of_pos hR ] );
    exact h_cauchy_schwarz_integral;
  -- Let $K = \frac{1}{4\pi^2} \int_0^{2\pi} \frac{R}{|R e^{it} - c|^2} dt$.
  obtain ⟨K, hK⟩ : ∃ K > 0, ∫ t in (0)..2 * Real.pi, R / ‖R * Complex.exp (Complex.I * t) - c‖ ^ 2 ≤ K := by
    exact ⟨ Max.max ( ∫ t in ( 0 : ℝ )..2 * Real.pi, R / ‖R * Complex.exp ( Complex.I * t ) - c‖ ^ 2 ) 1, by positivity, le_max_left _ _ ⟩;
  refine' ⟨ K / ( 4 * Real.pi ^ 2 ), div_pos hK.1 ( by positivity ), fun p => _ ⟩;
  refine le_trans ( pow_le_pow_left₀ ( norm_nonneg _ ) ( h_cauchy_schwarz p ) 2 ) ?_;
  convert mul_le_mul_of_nonneg_left ( h_cauchy_schwarz_integral p |> le_trans <| mul_le_mul_of_nonneg_left hK.2 <| by exact intervalIntegral.integral_nonneg ( by positivity ) fun _ _ => by positivity ) ( by positivity : 0 ≤ ( 1 / ( 2 * Real.pi ) ) ^ 2 ) using 1 <;> ring

/-
Acotación del funcional de evaluación.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

theorem evaluation_bounded
    (R : ℝ) (hR : 0 < R)
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    {P : Type*} [NormedAddCommGroup P] [NormedSpace ℂ P]
    (iso : P ≃ₗ[ℂ] Polynomial ℂ)
    (ι : P →L[ℂ] H)
    (h_sobolev : ∃ M > 0, ∀ p : P, (∫ t in (0)..2*Real.pi, ‖(iso p).eval (R * cexp (I * t))‖^2 * R) ≤ M * ‖ι p‖^2)
    (c : ℂ) (hc : ‖c‖ < R) :
    ∃ C, ∀ p : P, ‖(iso p).eval c‖ ≤ C * ‖ι p‖ := by
  obtain ⟨K, hK_pos, hK⟩ := evaluation_le_integral_norm_sq_uniform R hR c hc
  obtain ⟨M, hM_pos, hM⟩ := h_sobolev
  use Real.sqrt (K * M)
  intro p
  specialize hK (iso p)
  specialize hM p
  have h_comb : ‖(iso p).eval c‖^2 ≤ K * M * ‖ι p‖^2 := by
    calc ‖(iso p).eval c‖^2 ≤ K * ∫ t in (0)..2*Real.pi, ‖(iso p).eval (R * cexp (I * t))‖^2 * R := hK
    _ ≤ K * (M * ‖ι p‖^2) := by gcongr
    _ = K * M * ‖ι p‖^2 := by ring
  have h_nonneg : 0 ≤ K * M * ‖ι p‖^2 := by positivity
  rw [← Real.sq_sqrt h_nonneg] at h_comb
  rw [← Real.sq_sqrt (norm_nonneg ((iso p).eval c))] at h_comb
  -- This logic with squares is a bit messy, let ATP handle it
  convert Real.le_sqrt_of_sq_le ( h_comb.trans _ ) using 1 <;> norm_num [ mul_assoc, h_nonneg ];
  rotate_left;
  exact K * ( M * ‖ι p‖ ^ 2 );
  · rw [ Real.sq_sqrt ( by positivity ) ];
  · norm_num [ ← mul_assoc, hK_pos.le, hM_pos.le ]

/-
Definición del funcional de evaluación continuo en P.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

noncomputable def eval_continuous
    (R : ℝ) (hR : 0 < R)
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    {P : Type*} [NormedAddCommGroup P] [NormedSpace ℂ P]
    (iso : P ≃ₗ[ℂ] Polynomial ℂ)
    (ι : P →L[ℂ] H)
    (h_sobolev : ∃ M > 0, ∀ p : P, (∫ t in (0)..2*Real.pi, ‖(iso p).eval (R * cexp (I * t))‖^2 * R) ≤ M * ‖ι p‖^2)
    (c : ℂ) (hc : ‖c‖ < R) :
    P →L[ℂ] ℂ :=
  let bound := evaluation_bounded R hR iso ι h_sobolev c hc
  let C := Classical.choose bound
  LinearMap.mkContinuous
    { toFun := fun p => (iso p).eval c
      map_add' := fun p q => by simp
      map_smul' := fun a p => by simp }
    (C * ‖ι‖)
    (fun p => by
      have h_bound := Classical.choose_spec bound p
      calc ‖(iso p).eval c‖ ≤ C * ‖ι p‖ := h_bound
      _ ≤ C * (‖ι‖ * ‖p‖) := by
        apply mul_le_mul_of_nonneg_left
        · exact le_opNorm ι p
        · have : 0 ≤ ‖(iso 0).eval c‖ := norm_nonneg _
          have h0 := Classical.choose_spec bound 0
          simp at h0
          -- We need C ≥ 0. The bound holds for all p.
          -- If p=0, 0 ≤ C * 0 = 0.
          -- If there is some p with ι p ≠ 0, then C ≥ 0.
          -- If ι = 0, then eval must be 0 for bound to hold, so C can be anything.
          -- Let's just assume C ≥ 0 or take max C 0.
          -- Actually, let's look at evaluation_bounded. It returns ∃ C.
          -- I can fix C to be non-negative in the proof of evaluation_bounded or here.
          -- Let's just use abs C or max C 0 if needed, but wait.
          -- If I use `C * ‖ι p‖`, and `‖ι p‖` is non-neg, then `C` must be non-neg if LHS > 0.
          -- I'll just assume the ATP can handle the non-negativity or I'll use `max C 0`.
          -- Since there exists a polynomial p (like the constant polynomial 1) where ‖ι p‖ is non-zero, we can divide both sides of the inequality by ‖ι p‖ to get C ≥ 0.
          obtain ⟨p, hp⟩ : ∃ p : P, ‖ι p‖ ≠ 0 := by
            by_contra h_contra;
            obtain ⟨ M, hM₀, hM ⟩ := h_sobolev;
            specialize hM ( iso.symm 1 ) ; simp_all +decide [ ne_of_gt hR ];
            exact not_le_of_gt ( by positivity ) hM;
          exact le_of_not_gt fun h => hp <| by have := Classical.choose_spec bound p; nlinarith [ norm_nonneg ( Polynomial.eval c ( iso p ) ), norm_nonneg ( ι p ) ] ;
      _ = (C * ‖ι‖) * ‖p‖ := by ring
    )

/-
Extensión del funcional de evaluación a todo el espacio de Hilbert.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

noncomputable def extended_eval
    (R : ℝ) (hR : 0 < R)
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    {P : Type*} [NormedAddCommGroup P] [NormedSpace ℂ P]
    (iso : P ≃ₗ[ℂ] Polynomial ℂ)
    (ι : P →L[ℂ] H)
    (h_dense : DenseRange ι)
    (h_emb : IsUniformInducing ι)
    (h_sobolev : ∃ M > 0, ∀ p : P, (∫ t in (0)..2*Real.pi, ‖(iso p).eval (R * cexp (I * t))‖^2 * R) ≤ M * ‖ι p‖^2)
    (c : ℂ) (hc : ‖c‖ < R) :
    H →L[ℂ] ℂ :=
  (eval_continuous R hR iso ι h_sobolev c hc).extend ι h_dense h_emb

/-
Unicidad de la extensión del funcional.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

theorem extension_unique
    (R : ℝ) (hR : 0 < R)
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    {P : Type*} [NormedAddCommGroup P] [NormedSpace ℂ P]
    (iso : P ≃ₗ[ℂ] Polynomial ℂ)
    (ι : P →L[ℂ] H)
    (h_dense : DenseRange ι)
    (h_emb : IsUniformInducing ι)
    (h_sobolev : ∃ M > 0, ∀ p : P, (∫ t in (0)..2*Real.pi, ‖(iso p).eval (R * cexp (I * t))‖^2 * R) ≤ M * ‖ι p‖^2)
    (c : ℂ) (hc : ‖c‖ < R)
    (g : H →L[ℂ] ℂ)
    (hg : g.comp ι = eval_continuous R hR iso ι h_sobolev c hc) :
    g = extended_eval R hR iso ι h_dense h_emb h_sobolev c hc := by
      convert ContinuousLinearMap.extend_unique _ _ _ _ _ hg;
      any_goals assumption;
      · exact?;
      · convert ContinuousLinearMap.extend_unique _ _ _ _ _ _;
        exact hg

/-
El núcleo del funcional extendido es cerrado.
-/
open Complex MeasureTheory Set Metric ContinuousLinearMap Polynomial Topology Filter

theorem kernel_closed
    (R : ℝ) (hR : 0 < R)
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    {P : Type*} [NormedAddCommGroup P] [NormedSpace ℂ P]
    (iso : P ≃ₗ[ℂ] Polynomial ℂ)
    (ι : P →L[ℂ] H)
    (h_dense : DenseRange ι)
    (h_emb : IsUniformInducing ι)
    (h_sobolev : ∃ M > 0, ∀ p : P, (∫ t in (0)..2*Real.pi, ‖(iso p).eval (R * cexp (I * t))‖^2 * R) ≤ M * ‖ι p‖^2)
    (c : ℂ) (hc : ‖c‖ < R) :
    IsClosed (extended_eval R hR iso ι h_dense h_emb h_sobolev c hc ⁻¹' {0}) := by
  exact IsClosed.preimage (extended_eval R hR iso ι h_dense h_emb h_sobolev c hc).continuous isClosed_singleton