/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 817009b0-31fd-45c0-9ffd-a7a880c1d094

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the ideal $Y_a$ of polynomials vanishing at $a$ and prove that its image under the embedding into the Hilbert space $\mathcal{H}$ has a closure of codimension 1. This is done by extending the evaluation functional to a continuous linear functional on $\mathcal{H}$ and identifying the closure of the image of $Y_a$ with the kernel of this functional.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

theorem check_poly : True := by
  let p : Polynomial ℂ := Polynomial.X
  trivial

open Polynomial

#check Polynomial.evalRingHom
#check Module.finrank
#check Polynomial.aeval

open Polynomial

#check Submodule.topologicalClosure
#check DenseRange

/-
Let $\mathcal{H}$ be a Hilbert space such that the space of polynomials $\mathbb{P}[z]$ is dense in $\mathcal{H}$. Let $a \in \mathbb{C}$ be a bounded point evaluation (BPE) with respect to the norm of $\mathcal{H}$. Then, the algebraic ideal $Y_a = \{p \in \mathbb{P}[z] : p(a) = 0\}$ in $\mathcal{H}$ is a closed subspace of topological codimension exactly 1.
-/
open Polynomial

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The ideal of polynomials vanishing at a. -/
def Y (a : ℂ) : Submodule ℂ (Polynomial ℂ) :=
  LinearMap.ker (Polynomial.aeval a).toLinearMap

theorem codimension_one_of_bpe
    (iota : Polynomial ℂ →ₗ[ℂ] H)
    (h_dense : DenseRange iota)
    (a : ℂ)
    (h_bpe : ∃ C, ∀ p, ‖Polynomial.aeval a p‖ ≤ C * ‖iota p‖) :
    Module.finrank ℂ (H ⧸ (Submodule.map iota (Y a)).topologicalClosure) = 1 := by
  -- By the Bounded Point Evaluation (BPE) property, the linear map $\Phi_a: \mathcal{H} \to \mathbb{C}$ defined by $\Phi_a(f) = f(a)$ is bounded.
  obtain ⟨Φ_a, hΦ_a⟩ : ∃ Φ_a : H →L[ℂ] ℂ, ∀ p : ℂ[X], Φ_a (iota p) = (p.eval a) := by
    obtain ⟨C, hC⟩ := h_bpe;
    have h_dense : ∀ f : H, ∃ seq : ℕ → ℂ[X], Filter.Tendsto (fun n => iota (seq n)) Filter.atTop (nhds f) := by
      intro f
      have h_seq : f ∈ closure (Set.range iota) := by
        exact h_dense f;
      rw [ mem_closure_iff_seq_limit ] at h_seq;
      exact ⟨ fun n => Classical.choose ( h_seq.choose_spec.1 n ), by simpa only [ Classical.choose_spec ( h_seq.choose_spec.1 _ ) ] using h_seq.choose_spec.2 ⟩;
    have h_linear : ∀ f : H, ∃ y : ℂ, ∀ seq : ℕ → ℂ[X], Filter.Tendsto (fun n => iota (seq n)) Filter.atTop (nhds f) → Filter.Tendsto (fun n => (Polynomial.aeval a : ℂ[X] → ℂ) (seq n)) Filter.atTop (nhds y) := by
      intro f
      obtain ⟨seq, hseq⟩ := h_dense f
      have h_cauchy : CauchySeq (fun n => (Polynomial.aeval a : ℂ[X] → ℂ) (seq n)) := by
        have h_cauchy : CauchySeq (fun n => (iota (seq n))) := by
          exact hseq.cauchy_map;
        rw [ Metric.cauchySeq_iff ] at h_cauchy ⊢;
        intro ε hε; obtain ⟨ N, hN ⟩ := h_cauchy ( ε / ( Max.max C 1 ) ) ( div_pos hε ( by positivity ) ) ; use N; intros m hm n hn; specialize hN m hm n hn; simp_all +decide [ dist_eq_norm ];
        have := hC ( seq m - seq n ) ; simp_all +decide [ Polynomial.eval_sub ];
        exact this.trans_lt ( by rw [ lt_div_iff₀ ( by positivity ) ] at hN; nlinarith [ le_max_left C 1, le_max_right C 1, norm_nonneg ( iota ( seq m ) - iota ( seq n ) ) ] );
      obtain ⟨ y, hy ⟩ := cauchySeq_tendsto_of_complete h_cauchy;
      use y;
      intro seq' hseq'
      have h_diff : Filter.Tendsto (fun n => (Polynomial.aeval a : ℂ[X] → ℂ) (seq' n - seq n)) Filter.atTop (nhds 0) := by
        have h_diff : Filter.Tendsto (fun n => ‖iota (seq' n - seq n)‖) Filter.atTop (nhds 0) := by
          simpa using Filter.Tendsto.norm ( hseq'.sub hseq );
        exact squeeze_zero_norm ( fun n => hC _ ) ( by simpa using h_diff.const_mul C );
      simpa using h_diff.add hy;
    choose y hy using h_linear;
    have h_linear : ∀ f g : H, y (f + g) = y f + y g := by
      intro f g
      obtain ⟨seq_f, hseq_f⟩ := h_dense f
      obtain ⟨seq_g, hseq_g⟩ := h_dense g
      have h_seq_sum : Filter.Tendsto (fun n => iota (seq_f n + seq_g n)) Filter.atTop (nhds (f + g)) := by
        simpa only [ map_add ] using hseq_f.add hseq_g
      generalize_proofs at *;
      exact tendsto_nhds_unique ( hy ( f + g ) ( fun n => seq_f n + seq_g n ) h_seq_sum ) ( by simpa using Filter.Tendsto.add ( hy f seq_f hseq_f ) ( hy g seq_g hseq_g ) )
    have h_smul : ∀ c : ℂ, ∀ f : H, y (c • f) = c • y f := by
      intro c f
      obtain ⟨seq, hseq⟩ := h_dense f
      have h_seq_smul : Filter.Tendsto (fun n => iota (c • seq n)) Filter.atTop (nhds (c • f)) := by
        simpa using hseq.const_smul c
      generalize_proofs at *;
      exact tendsto_nhds_unique ( hy _ _ h_seq_smul ) ( by simpa using Filter.Tendsto.const_mul c ( hy _ _ hseq ) )
    have h_cont : Continuous y := by
      have h_cont : ∀ f : H, ‖y f‖ ≤ C * ‖f‖ := by
        intro f
        obtain ⟨seq, hseq⟩ := h_dense f
        have h_seq : Filter.Tendsto (fun n => ‖(Polynomial.aeval a : ℂ[X] → ℂ) (seq n)‖) Filter.atTop (nhds (‖y f‖)) := by
          exact Filter.Tendsto.norm ( hy f seq hseq )
        generalize_proofs at *;
        exact le_of_tendsto_of_tendsto' h_seq ( Filter.Tendsto.mul tendsto_const_nhds ( hseq.norm ) ) fun n => hC _
      generalize_proofs at *;
      refine' AddMonoidHomClass.continuous_of_bound ( show AddMonoidHom H ℂ from { toFun := y, map_zero' := by simpa using h_linear 0 0, map_add' := h_linear } ) C fun f => h_cont f
    generalize_proofs at *;
    refine' ⟨ { toFun := y, map_add' := h_linear, map_smul' := h_smul, cont := h_cont }, _ ⟩;
    intro p; specialize hy ( iota p ) ( fun _ => p ) ; aesop;
  -- Let $V = \{f \in \mathcal{H} : \Phi_a(f) = 0\}$ be the kernel of the linear functional $\Phi_a$.
  set V := LinearMap.ker Φ_a with hV_def;
  -- Since $\Phi_a$ is continuous and $\Phi_a(\mathbf{1}) = 1 \neq 0$, we know that $\mathbf{1} \notin V$. Therefore, the direct sum is preserved in the closure:
  have h_closure : (Submodule.map iota (Y a)).topologicalClosure = V := by
    refine' le_antisymm _ _;
    · refine' closure_minimal _ _;
      · intro x hx
        aesop;
      · exact isClosed_eq Φ_a.continuous continuous_const;
    · intro x hx
      have h_seq : ∃ seq : ℕ → ℂ[X], Filter.Tendsto (fun n => iota (seq n)) Filter.atTop (nhds x) := by
        have := h_dense x;
        rw [ mem_closure_iff_seq_limit ] at this;
        exact ⟨ fun n => Classical.choose ( this.choose_spec.1 n ), by simpa only [ Classical.choose_spec ( this.choose_spec.1 _ ) ] using this.choose_spec.2 ⟩;
      obtain ⟨ seq, hseq ⟩ := h_seq;
      -- Consider the sequence $q_n(z) = seq_n(z) - seq_n(a) \cdot 1$.
      set q : ℕ → ℂ[X] := fun n => seq n - Polynomial.C (seq n |> Polynomial.eval a) * 1 with hq_def;
      have hq_seq : Filter.Tendsto (fun n => iota (q n)) Filter.atTop (nhds x) := by
        have hq_seq : Filter.Tendsto (fun n => seq n |> Polynomial.eval a) Filter.atTop (nhds 0) := by
          have := hseq;
          simpa [ hΦ_a ] using Filter.Tendsto.congr ( by aesop ) ( Φ_a.continuous.continuousAt.tendsto.comp this ) |> fun h => h.trans ( by aesop );
        convert hseq.sub ( hq_seq.smul_const ( iota 1 ) ) using 2 <;> simp +decide [ hq_def ];
        convert iota.map_smul ( Polynomial.eval a ( seq ‹_› ) ) 1 using 1 ; simp +decide [ Polynomial.smul_eq_C_mul ];
      refine' mem_closure_of_tendsto hq_seq _;
      simp +decide [ Y ];
      exact ⟨ 0, fun n _ => ⟨ q n, by simp +decide [ hq_def ], rfl ⟩ ⟩;
  rw [ h_closure ];
  -- Since $\Phi_a$ is continuous and $\Phi_a(\mathbf{1}) = 1 \neq 0$, we know that $\mathbf{1} \notin V$. Therefore, the quotient space $H / V$ is isomorphic to $\mathbb{C}$.
  have h_quotient : (H ⧸ V) ≃ₗ[ℂ] ℂ := by
    have h_quotient : Function.Surjective Φ_a := by
      intro c;
      exact ⟨ iota ( Polynomial.C c ), by simp +decide [ hΦ_a ] ⟩;
    refine' ( LinearMap.quotKerEquivOfSurjective _ h_quotient );
  simpa using LinearEquiv.finrank_eq h_quotient