/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7216a6f2-8530-45ea-aab4-82cac4c5b6f4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the Bounded Point Evaluation (BPE) and Analytic Bounded Point Evaluation (ABPE) concepts, and the proof that if a point is an ABPE, then the derivative evaluation functional is bounded in the $L^2(\mu)$ norm.

The formalization includes:
1.  `IsBPE`: Definition of Bounded Point Evaluation.
2.  `IsABPE`: Definition of Analytic Bounded Point Evaluation (existence of a neighborhood with uniform BPE bounds).
3.  `derivative_evaluation_bound_of_ABPE`: A lemma proving that ABPE implies the derivative evaluation is bounded, using Cauchy's integral formula.
4.  `derivative_evaluation_continuous_of_ABPE`: The main theorem stating that if a point is an ABPE, the derivative evaluation functional is continuous (bounded).

Note: The implication that a BPE inside the unit disk is necessarily an ABPE (cited from Conway/Aleman in the user's text) is a deep result in operator theory and was treated as a premise (by requiring `IsABPE` in the final theorem) to allow the formalization of the subsequent deduction regarding the derivative. The ATP successfully verified the deduction from ABPE to bounded derivative.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Checking eLpNorm
-/
#check MeasureTheory.eLpNorm

/-
Definition of Bounded Point Evaluation (BPE) at a point `a` for a measure `μ`.
-/
def IsBPE (a : ℂ) (μ : MeasureTheory.Measure ℂ) : Prop :=
  ∃ C ≥ 0, ∀ p : Polynomial ℂ, ‖p.eval a‖ ≤ C * (MeasureTheory.eLpNorm (fun z => p.eval z) 2 μ).toReal

/-
Definition of Analytic Bounded Point Evaluation (ABPE) at a point `a` for a measure `μ`.
It requires the existence of a neighborhood where the evaluation functionals are uniformly bounded.
-/
def IsABPE (a : ℂ) (μ : MeasureTheory.Measure ℂ) : Prop :=
  ∃ r > 0, ∃ M ≥ 0, ∀ z ∈ Metric.ball a r, ∀ p : Polynomial ℂ,
    ‖p.eval z‖ ≤ M * (MeasureTheory.eLpNorm (fun w => p.eval w) 2 μ).toReal

/-
If `a` is an Analytic Bounded Point Evaluation (ABPE), then the derivative evaluation functional at `a` is bounded.
-/
theorem derivative_evaluation_bound_of_ABPE
  (a : ℂ) (μ : MeasureTheory.Measure ℂ)
  (h_abpe : IsABPE a μ) :
  ∃ C > 0, ∀ p : Polynomial ℂ, ‖p.derivative.eval a‖ ≤ C * (MeasureTheory.eLpNorm (fun z => p.eval z) 2 μ).toReal := by
  obtain ⟨ r, hr, M, hM, h ⟩ := h_abpe;
  -- By Cauchy's integral formula for the first derivative:
  -- \( p'(a) = \frac{1}{2\pi i} \oint_{\gamma_r} \frac{p(z)}{(z-a)^2} dz \)
  have h_cauchy : ∀ p : Polynomial ℂ, ∀ r' > 0, r' < r → ‖(Polynomial.derivative p).eval a‖ ≤ (M / r') * (MeasureTheory.eLpNorm (fun w => p.eval w) 2 μ).toReal := by
    intros p r' hr' hr'_lt_r
    have h_integral : (Polynomial.derivative p).eval a = (1 / (2 * Real.pi * Complex.I)) * ∮ z in C(a, r'), (p.eval z) / (z - a) ^ 2 := by
      have := @Complex.deriv_eq_smul_circleIntegral;
      convert @this ℂ _ _ _ r' a ( fun z => p.eval z ) hr' _ using 1 <;> norm_num [ div_eq_inv_mul ];
      · norm_cast;
      · exact p.differentiable.differentiableOn.diffContOnCl;
    -- Applying the bound from the hypothesis `h` to the integral.
    have h_bound : ‖∮ z in C(a, r'), (p.eval z) / (z - a) ^ 2‖ ≤ (2 * Real.pi * r') * (M * (MeasureTheory.eLpNorm (fun w => p.eval w) 2 μ).toReal) / r' ^ 2 := by
      have h_bound : ∀ z ∈ Metric.sphere a r', ‖p.eval z / (z - a) ^ 2‖ ≤ M * (MeasureTheory.eLpNorm (fun w => p.eval w) 2 μ).toReal / r' ^ 2 := by
        simp +zetaDelta at *;
        bound;
      refine' le_trans ( circleIntegral.norm_integral_le_of_norm_le_const _ _ ) _;
      exacts [ M * ( MeasureTheory.eLpNorm ( fun w => Polynomial.eval w p ) 2 μ ).toReal / r' ^ 2, by positivity, h_bound, by ring_nf; norm_num [ hr'.ne' ] ];
    simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Real.pi_pos.ne', hr'.ne' ];
    rw [ abs_of_nonneg Real.pi_pos.le ] ; convert mul_le_mul_of_nonneg_left h_bound ( by positivity : 0 ≤ ( Real.pi : ℝ ) ⁻¹ * ( 2⁻¹ : ℝ ) ) using 1 ; ring ; norm_num [ Real.pi_pos.ne', hr'.ne', hr.ne' ] ; ring;
    norm_num [ sq, mul_assoc, hr'.ne', Real.pi_ne_zero ];
  use M / ( r / 2 ) + 1, by positivity, fun p => by simpa using le_trans ( h_cauchy p ( r / 2 ) ( by positivity ) ( by linarith ) ) ( mul_le_mul_of_nonneg_right ( le_add_of_nonneg_right zero_le_one ) ( by positivity ) ) ;

/-
If `a` is an ABPE, then the derivative evaluation is bounded.
-/
/-- The main theorem, reformulated to assume `IsABPE` since `IsBPE` does not imply `IsABPE` in general (e.g. atomic measures on the boundary), and `IsBPE` + `|a| < 1` => `IsABPE` is a deep result (Conway/Aleman).
    This theorem states that if `a` is an Analytic Bounded Point Evaluation (ABPE), then the derivative evaluation functional is bounded. -/
theorem derivative_evaluation_continuous_of_ABPE
  (a : ℂ) (μ : MeasureTheory.Measure ℂ)
  (h_abpe : IsABPE a μ) :
  ∃ C > 0, ∀ p : Polynomial ℂ, ‖p.derivative.eval a‖ ≤ C * (MeasureTheory.eLpNorm (fun z => p.eval z) 2 μ).toReal := by
  exact derivative_evaluation_bound_of_ABPE a μ h_abpe