/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e2497870-af45-490c-805c-3da648ab4eb4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of Y, eval_functional, and Phi. Proof that Phi(ι p) a = p(a).
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (hι_dense : (LinearMap.range ι).topologicalClosure = ⊤)
variable (hι_inj : Function.Injective ι)
variable (A : Finset ℂ)
variable (N : ℕ)
variable (hA_card : A.card = N)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

noncomputable def Y : Submodule ℂ H :=
  Submodule.map ι (Submodule.span ℂ {p | ∀ a ∈ A, p.eval a = 0})

noncomputable def eval_functional (a : A) : H →L[ℂ] ℂ :=
  Classical.choose (h_bpe a a.2)

theorem eval_functional_apply (a : A) (p : Polynomial ℂ) :
    eval_functional ι A h_bpe a (ι p) = p.eval (a : ℂ) :=
  Classical.choose_spec (h_bpe a a.2) p

noncomputable def Phi : H →L[ℂ] (A → ℂ) :=
  ContinuousLinearMap.pi (fun a => eval_functional ι A h_bpe a)

theorem Phi_apply (x : H) (a : A) :
    Phi ι A h_bpe x a = eval_functional ι A h_bpe a x :=
  rfl

theorem Phi_apply_poly (p : Polynomial ℂ) (a : A) :
    Phi ι A h_bpe (ι p) a = p.eval (a : ℂ) := by
  simp [Phi_apply, eval_functional_apply]

/-
Definition of Lagrange basis in H.
Proof that Phi maps Lagrange basis to standard basis vectors.
-/
noncomputable def LagrangeBasis (a : A) : H :=
  ι (Lagrange.basis A id (a : ℂ))

theorem Phi_LagrangeBasis (a b : A) :
    Phi ι A h_bpe (LagrangeBasis ι A a) b = if a = b then 1 else 0 := by
      convert Phi_apply_poly ι A h_bpe ( Lagrange.basis A id a ) b using 1;
      split_ifs with h <;> simp_all +decide [ Lagrange.basis ];
      · simp +decide [ Lagrange.basisDivisor, Polynomial.eval_prod ];
        rw [ Finset.prod_eq_one fun x hx => by rw [ inv_mul_cancel₀ ] ; exact sub_ne_zero_of_ne <| by aesop ];
      · rw [ Polynomial.eval_prod, Finset.prod_eq_zero ( Finset.mem_erase_of_ne_of_mem ( by aesop ) b.2 ) ] ; aesop

/-
The map $\Phi$ is surjective.
-/
theorem Phi_surjective : Function.Surjective (Phi ι A h_bpe) := by
  intro f
  let f' := fun a : A => f a
  have h_sum : ∃ x : H, ∀ a : A, (Phi ι A h_bpe x) a = f' a := by
    -- By definition of Lagrange basis, we have $\Phi(\sum_{a \in A} v(a) \cdot \text{LagrangeBasis}(a)) = \sum_{a \in A} v(a) \cdot \Phi(\text{LagrangeBasis}(a))$.
    have h_sum : ∀ v : A → ℂ, ∃ x : H, ∀ a : A, (Phi ι A h_bpe x) a = v a := by
      intro v
      use ∑ a : A, v a • LagrangeBasis ι A a
      intro a
      simp [Phi_LagrangeBasis]
    generalize_proofs at *;
    exact h_sum f'
  generalize_proofs at *;
  exact ⟨ h_sum.choose, funext h_sum.choose_spec ⟩

/-
Prove that Y is contained in the kernel of Phi, and thus the closure of Y is contained in the kernel of Phi.
-/
theorem Y_le_ker_Phi : Y ι A ≤ LinearMap.ker (Phi ι A h_bpe) := by
  rintro x ⟨ p, hp, rfl ⟩;
  refine' Submodule.span_induction _ _ _ _ hp;
  · simp +decide [ funext_iff, Phi ];
    exact fun p hp a ha => by rw [ eval_functional_apply ] ; exact hp a ha;
  · simp +decide;
  · simp +contextual [ LinearMap.mem_ker ];
  · simp +contextual [ LinearMap.mem_ker ]

theorem closure_Y_le_ker_Phi : (Y ι A).topologicalClosure ≤ LinearMap.ker (Phi ι A h_bpe) := by
  refine' closure_minimal _ _;
  · rintro _ ⟨ p, hp, rfl ⟩;
    refine' Submodule.span_induction _ _ _ _ hp;
    · simp +contextual [ funext_iff, Phi_apply ];
      exact fun p hp a ha => by rw [ eval_functional_apply ] ; exact hp a ha;
    · simp +decide;
    · simp +contextual [ map_add ];
    · simp +contextual [ LinearMap.mem_ker ];
  · exact isClosed_eq ( ContinuousLinearMap.continuous _ ) continuous_zero

/-
Y is the intersection of the kernel of Phi and the range of ι.
-/
theorem Y_eq_ker_Phi_inf_range_iota : Y ι A = LinearMap.ker (Phi ι A h_bpe) ⊓ LinearMap.range ι := by
  ext x;
  constructor <;> intro hx <;> simp_all +decide [ Submodule.mem_map, Submodule.mem_inf ];
  · exact ⟨ by simpa using Y_le_ker_Phi ι A h_bpe hx, by rcases Submodule.mem_map.mp hx with ⟨ p, hp, rfl ⟩ ; exact ⟨ p, rfl ⟩ ⟩;
  · obtain ⟨ hx₁, y, rfl ⟩ := hx; simp_all +decide [ funext_iff, Phi ] ;
    exact Submodule.mem_map_of_mem ( Submodule.subset_span fun a ha => by simpa [ eval_functional_apply ] using hx₁ a ha )

/-
Defined `proj` manually.
Defined `CorrectionMap` using `proj` and `A.attach` with correct arguments.
Proved `CorrectionMap_apply`.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (A : Finset ℂ)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

noncomputable def proj (a : {x // x ∈ A}) : ({x // x ∈ A} → ℂ) →L[ℂ] ℂ where
  toFun f := f a
  map_add' f g := rfl
  map_smul' c f := rfl
  cont := continuous_apply a

noncomputable def CorrectionMap : H →L[ℂ] H :=
  ∑ a ∈ A.attach, ContinuousLinearMap.smulRight
    ((proj A a).comp (Phi ι A h_bpe))
    (LagrangeBasis ι A a)

theorem CorrectionMap_apply (y : H) :
    CorrectionMap ι A h_bpe y = ∑ a ∈ A.attach, (Phi ι A h_bpe y a) • LagrangeBasis ι A a := by
  simp [CorrectionMap, proj]

/-
$\Phi(\text{CorrectionMap}(y)) = \Phi(y)$.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (A : Finset ℂ)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

theorem Phi_CorrectionMap (y : H) :
    Phi ι A h_bpe (CorrectionMap ι A h_bpe y) = Phi ι A h_bpe y := by
      have h_phi_lagrange : ∀ a b : A, (Phi ι A h_bpe (LagrangeBasis ι A a)) b = if a = b then 1 else 0 := by
        exact?;
      ext a;
      simp +decide [ CorrectionMap_apply, h_phi_lagrange ]

/-
The image of the correction map is contained in the range of $\iota$.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (A : Finset ℂ)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

theorem CorrectionMap_mem_range_iota (y : H) :
    CorrectionMap ι A h_bpe y ∈ LinearMap.range ι := by
  rw [CorrectionMap_apply]
  apply Submodule.sum_mem
  intro a _
  apply Submodule.smul_mem
  exact LinearMap.mem_range.mpr ⟨Lagrange.basis A id (a : ℂ), rfl⟩

/-
If $y$ is in the kernel of $\Phi$, then the correction map at $y$ is zero.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (A : Finset ℂ)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

theorem CorrectionMap_eq_zero_of_mem_ker (y : H) (hy : y ∈ LinearMap.ker (Phi ι A h_bpe)) :
    CorrectionMap ι A h_bpe y = 0 := by
  rw [CorrectionMap_apply]
  rw [LinearMap.mem_ker] at hy
  simp [hy]

/-
$y - \text{CorrectionMap}(y) \in Y$ for $y \in \text{range } \iota$.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (A : Finset ℂ)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

theorem range_iota_sub_correction_subset_Y (y : H) (hy : y ∈ LinearMap.range ι) :
    y - CorrectionMap ι A h_bpe y ∈ Y ι A := by
      have h_y_minus_CorrectionMap_in_Y : y - CorrectionMap ι A h_bpe y ∈ LinearMap.ker (Phi ι A h_bpe) ⊓ LinearMap.range ι := by
        refine' ⟨ _, _ ⟩;
        · simp +decide [ Phi_CorrectionMap ];
        · exact Submodule.sub_mem _ hy ( CorrectionMap_mem_range_iota ι A h_bpe y );
      rwa [ Y_eq_ker_Phi_inf_range_iota ]

/-
The kernel of $\Phi$ is contained in the closure of $Y$.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (A : Finset ℂ)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

theorem ker_Phi_le_closure_Y (hι_dense : (LinearMap.range ι).topologicalClosure = ⊤) :
    LinearMap.ker (Phi ι A h_bpe) ≤ (Y ι A).topologicalClosure := by
      intro x hx; by_contra h_contra; simp_all +decide [ SetLike.le_def ] ;
      -- Since the range of $\iota$ is dense, any $x \in \ker \Phi$ is a limit of a sequence $x_n \in \text{range } \iota$.
      obtain ⟨x_n, hx_n⟩ : ∃ x_n : ℕ → H, (∀ n, x_n n ∈ LinearMap.range ι) ∧ Filter.Tendsto x_n Filter.atTop (nhds x) := by
        have h_dense : x ∈ (LinearMap.range ι).topologicalClosure := by
          aesop;
        exact mem_closure_iff_seq_limit.mp h_dense;
      -- We correct this sequence by subtracting the Lagrange interpolation of the values $\Phi(x_n)$, defining $y_n = x_n - \text{CorrectionMap}(x_n)$.
      set y_n : ℕ → H := fun n => x_n n - CorrectionMap ι A h_bpe (x_n n) with hy_n_def
      have hy_n_mem_Y : ∀ n, y_n n ∈ Y ι A := by
        exact fun n => range_iota_sub_correction_subset_Y ι A h_bpe _ ( hx_n.1 n ) |> fun h => by simpa using h;
      have hy_n_tendsto_x : Filter.Tendsto y_n Filter.atTop (nhds x) := by
        -- Since $\text{CorrectionMap}(x_n) \to \text{CorrectionMap}(x) = 0$, we have $y_n \to x$.
        have h_correction_map_zero : Filter.Tendsto (fun n => CorrectionMap ι A h_bpe (x_n n)) Filter.atTop (nhds 0) := by
          have hy_n_tendsto_x : Filter.Tendsto (fun n => CorrectionMap ι A h_bpe (x_n n)) Filter.atTop (nhds (CorrectionMap ι A h_bpe x)) := by
            exact ContinuousLinearMap.continuous _ |> fun h => h.continuousAt.tendsto.comp hx_n.2;
          have := CorrectionMap_eq_zero_of_mem_ker ι A h_bpe x ?_ <;> aesop
          skip
        generalize_proofs at *; (
        simpa using hx_n.2.sub h_correction_map_zero)
      have hy_n_tendsto_x_in_closure : x ∈ (Y ι A).topologicalClosure := by
        exact mem_closure_of_tendsto hy_n_tendsto_x ( Filter.Eventually.of_forall hy_n_mem_Y )
      contradiction

/-
The closure of Y is equal to the kernel of Phi.
-/
open Polynomial Module FiniteDimensional

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (ι : Polynomial ℂ →ₗ[ℂ] H)
variable (hι_inj : Function.Injective ι)
variable (A : Finset ℂ)
variable (N : ℕ)
variable (hA_card : A.card = N)
variable (h_bpe : ∀ a ∈ A, ∃ (f : H →L[ℂ] ℂ), ∀ p, f (ι p) = p.eval a)

theorem closure_Y_eq_ker_Phi (hι_dense : (LinearMap.range ι).topologicalClosure = ⊤) :
    (Y ι A).topologicalClosure = LinearMap.ker (Phi ι A h_bpe) := by
  apply le_antisymm
  · exact closure_Y_le_ker_Phi ι A h_bpe
  · exact ker_Phi_le_closure_Y ι A h_bpe hι_dense