/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 150f7933-0f3b-45f3-a300-9c56a93b65a0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We prove the Codimension Dichotomy Theorem for the closure of polynomials in a Hilbert space.
We define `is_BPE` (Bounded Point Evaluation) and the subspace `V'` of polynomials vanishing at a point `a`.
We prove that if `a` is a BPE, `V'` has codimension 1 (`codimension_one_of_BPE`).
We prove that if `a` is not a BPE, `V'` is dense in `H`, so it has codimension 0 (`codimension_zero_of_not_BPE`).
Finally, we combine these into the main theorem `codimension_dichotomy`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check Polynomial
#check InnerProductSpace
#check Module.rank

open Polynomial

#check Polynomial.leval

/-
The subspace of polynomials that vanish at a.
-/
open Polynomial InnerProductSpace

noncomputable def PolyKer (a : ℂ) : Submodule ℂ (Polynomial ℂ) :=
  LinearMap.ker (Polynomial.leval a)

/-
Definitions for Bounded Point Evaluation and the subspace V'.
-/
open Polynomial InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

def is_BPE (ι : Polynomial ℂ →ₗ[ℂ] H) (a : ℂ) : Prop :=
  ∃ C > 0, ∀ p, ‖p.eval a‖ ≤ C * ‖ι p‖

noncomputable def V' (ι : Polynomial ℂ →ₗ[ℂ] H) (a : ℂ) : Submodule ℂ H :=
  Submodule.topologicalClosure (Submodule.map ι (PolyKer a))

/-
If a is a Bounded Point Evaluation, then the codimension of V' is 1.
-/
open Polynomial InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

theorem codimension_one_of_BPE
  (ι : Polynomial ℂ →ₗ[ℂ] H) (hι_dense : DenseRange ι) (hι_inj : Function.Injective ι) (a : ℂ)
  (h_bpe : is_BPE ι a) : Module.rank ℂ ↥(V' ι a)ᗮ = 1 := by
    obtain ⟨ C, hC_pos, hC ⟩ := h_bpe;
    -- Let $f$ be the unique continuous linear functional on $H$ such that $f(\iota p) = p(a)$ for all $p \in \mathbb{C}[z]$.
    obtain ⟨f, hf⟩ : ∃ f : H →L[ℂ] ℂ, ∀ p : Polynomial ℂ, f (ι p) = p.eval a := by
      have h_bounded : ∃ f : ↥(LinearMap.range ι) →L[ℂ] ℂ, ∀ p : Polynomial ℂ, f ⟨ι p, LinearMap.mem_range_self ι p⟩ = p.eval a := by
        have h_bounded : ∃ f : ↥(LinearMap.range ι) →ₗ[ℂ] ℂ, ∀ p : Polynomial ℂ, f ⟨ι p, LinearMap.mem_range_self ι p⟩ = p.eval a := by
          refine' ⟨ _, _ ⟩;
          refine' { .. };
          use fun x => Polynomial.eval a ( Classical.choose ( LinearMap.mem_range.mp x.2 ) );
          all_goals simp +decide [ hι_inj.eq_iff ];
          · intro a_1 x hx a_2 x_1 hx_1
            have h_eq : Classical.choose (LinearMap.mem_range.mp (show a_1 + a_2 ∈ LinearMap.range ι from by
                                                                    exact ⟨ x + x_1, by simp +decide [ hx, hx_1 ] ⟩)) = Classical.choose (LinearMap.mem_range.mp (show a_1 ∈ LinearMap.range ι from by
                                                                                                                                                                  exact ⟨ x, hx ⟩)) + Classical.choose (LinearMap.mem_range.mp (show a_2 ∈ LinearMap.range ι from by
                                                                                                                                                                                                                                                            exact ⟨ x_1, hx_1 ⟩)) := by
                                                                                                                                                                                                                                                            all_goals generalize_proofs at *;
                                                                                                                                                                                                                                                            exact hι_inj ( by have := Classical.choose_spec ‹∃ x : ℂ[X], ι x = a_1 + a_2›; have := Classical.choose_spec ‹∃ x : ℂ[X], ι x = a_1›; have := Classical.choose_spec ‹∃ x : ℂ[X], ι x = a_2›; aesop )
            generalize_proofs at *;
            rw [ h_eq, Polynomial.eval_add ];
          · intro m x p hp
            have h_eq : Classical.choose (LinearMap.mem_range.mp (show ι (m • p) ∈ LinearMap.range ι from LinearMap.mem_range_self ι (m • p))) = m • Classical.choose (LinearMap.mem_range.mp (show ι p ∈ LinearMap.range ι from LinearMap.mem_range_self ι p)) := by
                                                                                                                                                                                                have := Classical.choose_spec ( LinearMap.mem_range.mp ( show ι ( m • p ) ∈ LinearMap.range ι from LinearMap.mem_range_self ι ( m • p ) ) ) ; have := Classical.choose_spec ( LinearMap.mem_range.mp ( show ι p ∈ LinearMap.range ι from LinearMap.mem_range_self ι p ) ) ; aesop;
            aesop;
        obtain ⟨ f, hf ⟩ := h_bounded;
        have h_bounded : ∀ x : ↥(LinearMap.range ι), ‖f x‖ ≤ C * ‖x‖ := by
          rintro ⟨ x, hx ⟩ ; obtain ⟨ p, rfl ⟩ := hx; aesop;
        refine' ⟨ { toFun := f, map_add' := _, map_smul' := _, cont := _ }, hf ⟩;
        refine' AddMonoidHomClass.continuous_of_bound f C fun x => h_bounded x;
      obtain ⟨ f, hf ⟩ := h_bounded;
      have := exists_extension_norm_eq ( LinearMap.range ι ) f;
      exact ⟨ this.choose, fun p => this.choose_spec.1 ⟨ ι p, LinearMap.mem_range_self ι p ⟩ ▸ hf p ⟩;
    -- Since $f$ is continuous and $f(\iota p) = p(a)$ for all $p \in \mathbb{C}[z]$, we have $V' = \ker f$.
    have hV'_ker_f : V' ι a = LinearMap.ker f := by
      refine' le_antisymm _ _;
      · refine' closure_minimal _ _;
        · intro x hx
          aesop;
        · exact isClosed_eq f.continuous continuous_const;
      · intro x hx
        have h_seq : ∃ seq : ℕ → Polynomial ℂ, Filter.Tendsto (fun n => ι (seq n)) Filter.atTop (nhds x) := by
          have := hι_dense x;
          rw [ mem_closure_iff_seq_limit ] at this;
          exact ⟨ fun n => Classical.choose ( this.choose_spec.1 n ), by simpa only [ Classical.choose_spec ( this.choose_spec.1 _ ) ] using this.choose_spec.2 ⟩;
        obtain ⟨ seq, hseq ⟩ := h_seq;
        have h_seq_eval : Filter.Tendsto (fun n => (seq n).eval a) Filter.atTop (nhds 0) := by
          simpa [ hf ] using Filter.Tendsto.congr ( by aesop ) ( f.continuous.continuousAt.tendsto.comp hseq ) |> fun h => h.trans ( by aesop );
        have h_seq_eval : Filter.Tendsto (fun n => ι (seq n - Polynomial.C ((seq n).eval a))) Filter.atTop (nhds x) := by
          have h_seq_eval : Filter.Tendsto (fun n => ι (Polynomial.C ((seq n).eval a))) Filter.atTop (nhds 0) := by
            have h_seq_eval : Filter.Tendsto (fun n => Polynomial.eval a (seq n) • ι (Polynomial.C 1)) Filter.atTop (nhds 0) := by
              simpa using h_seq_eval.smul_const ( ι ( Polynomial.C 1 ) );
            convert h_seq_eval using 1;
            ext; simp +decide [ Polynomial.smul_eq_C_mul ] ;
            convert ι.map_smul ( Polynomial.eval a ( seq ‹_› ) ) 1 using 1 ; simp +decide [ Polynomial.smul_eq_C_mul ];
          simpa using hseq.sub h_seq_eval;
        exact mem_closure_of_tendsto h_seq_eval ( Filter.Eventually.of_forall fun n => Set.mem_image_of_mem _ <| show seq n - Polynomial.C ( Polynomial.eval a ( seq n ) ) ∈ PolyKer a from by simp +decide [ PolyKer ] );
    -- Since $f$ is continuous and $f(\iota p) = p(a)$ for all $p \in \mathbb{C}[z]$, we have $V' = \ker f$. Therefore, $V'^\perp = \operatorname{span} \{k\}$ for some $k \in H$.
    obtain ⟨k, hk⟩ : ∃ k : H, ∀ x : H, x ∈ (LinearMap.ker f)ᗮ ↔ ∃ c : ℂ, x = c • k := by
      obtain ⟨k, hk⟩ : ∃ k : H, ∀ x : H, f x = inner ℂ k x := by
        exact ⟨ ( ContinuousLinearMap.adjoint f ) 1, fun x => by simp +decide [ ContinuousLinearMap.adjoint_inner_left ] ⟩;
      use k;
      intro x; simp +decide [ hk, Submodule.mem_orthogonal' ] ;
      constructor;
      · intro hx;
        by_cases hk_zero : k = 0;
        · specialize hf 1; aesop;
        · use ⟪k, x⟫_ℂ / ⟪k, k⟫_ℂ;
          refine' ext_inner_right ℂ _;
          intro v; specialize hx ( v - ( ⟪k, v⟫_ℂ / ⟪k, k⟫_ℂ ) • k ) ; simp_all +decide [ inner_sub_right, inner_smul_right ] ;
          simp_all +decide [ div_eq_inv_mul, inner_smul_left, inner_smul_right ];
          linear_combination' hx;
      · rintro ⟨ c, rfl ⟩ u hu; simp +decide [ hu, inner_smul_left ] ;
    have h_span : (LinearMap.ker f)ᗮ = Submodule.span ℂ {k} := by
      ext x; simp [hk];
      simp +decide [ Submodule.mem_span_singleton, eq_comm ];
    by_cases hk_zero : k = 0 <;> simp_all +decide [ Submodule.span_singleton_eq_bot ];
    · simp_all +decide [ Submodule.eq_top_iff' ];
      exact absurd ( hf 1 ) ( by norm_num );
    · rw [ hV'_ker_f, h_span, rank_span_set ] ; aesop;
      exact linearIndependent_unique _ hk_zero

/-
If a is not a Bounded Point Evaluation, then the codimension of V' is 0.
-/
open Polynomial InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

theorem codimension_zero_of_not_BPE
  (ι : Polynomial ℂ →ₗ[ℂ] H) (hι_dense : DenseRange ι) (hι_inj : Function.Injective ι) (a : ℂ)
  (h_not_bpe : ¬ is_BPE ι a) : Module.rank ℂ ↥(V' ι a)ᗮ = 0 := by
    -- Since ι 1 and ι X are in V', we can show that ι (X^n) is in V' for all n ≥ 0.
    have h_ι_X_pow_in_V' : ∀ n : ℕ, ι (Polynomial.X ^ n) ∈ V' ι a := by
      intro n
      induction' n with n ih;
      · have h_ι_1_in_V' : ∀ n : ℕ, ∃ p : Polynomial ℂ, p ∈ PolyKer a ∧ ‖ι 1 - ι p‖ < 1 / (n + 1) := by
          intro n
          obtain ⟨h_n, hh_n⟩ : ∃ h_n : Polynomial ℂ, ‖ι h_n‖ < 1 / (n + 1) ∧ h_n.eval a = 1 := by
            contrapose! h_not_bpe;
            refine' ⟨ ( n + 1 : ℝ ), by positivity, fun p => _ ⟩;
            by_cases hp : p.eval a = 0 <;> simp_all +decide [ mul_comm ];
            · positivity;
            · specialize h_not_bpe ( Polynomial.C ( 1 / p.eval a ) * p ) ; simp_all +decide [ Polynomial.eval_C, Polynomial.eval_mul, Polynomial.eval_X ];
              rw [ inv_eq_one_div, div_le_iff₀' ] at h_not_bpe <;> norm_num at *;
              · rw [ show ι ( Polynomial.C ( Polynomial.eval a p ) ⁻¹ * p ) = ( Polynomial.eval a p ) ⁻¹ • ι p from ?_ ] at h_not_bpe;
                · rw [ norm_smul, norm_inv ] at h_not_bpe;
                  nlinarith [ norm_pos_iff.mpr hp, mul_inv_cancel₀ ( norm_ne_zero_iff.mpr hp ), mul_nonneg ( Nat.cast_nonneg n : ( 0 : ℝ ) ≤ n ) ( norm_nonneg ( ι p ) ) ];
                · convert ι.map_smul ( Polynomial.eval a p ) ⁻¹ p using 1;
                  exact congr_arg _ ( by ext; simp +decide [ Polynomial.smul_eq_C_mul ] );
              · positivity;
          refine' ⟨ 1 - h_n, _, _ ⟩ <;> simp_all +decide [ PolyKer ];
        choose p hp using h_ι_1_in_V';
        have h_ι_1_in_V' : Filter.Tendsto (fun n => ι (p n)) Filter.atTop (nhds (ι 1)) := by
          rw [ tendsto_iff_norm_sub_tendsto_zero ];
          exact squeeze_zero ( fun _ => norm_nonneg _ ) ( fun n => by simpa only [ norm_sub_rev ] using le_of_lt ( hp n |>.2 ) ) ( tendsto_one_div_add_atTop_nhds_zero_nat );
        exact mem_closure_of_tendsto h_ι_1_in_V' ( Filter.Eventually.of_forall fun n => Submodule.mem_map_of_mem ( hp n |>.1 ) );
      · have h_ι_X_pow_in_V' : ι (Polynomial.X ^ (n + 1) - Polynomial.C a * Polynomial.X ^ n) ∈ V' ι a := by
          have h_ι_X_pow_in_V' : ∀ p : Polynomial ℂ, p.eval a = 0 → ι p ∈ V' ι a := by
            exact fun p hp => subset_closure <| Submodule.mem_map_of_mem <| LinearMap.mem_ker.mpr hp;
          exact h_ι_X_pow_in_V' _ ( by simp +decide [ pow_succ' ] );
        convert Submodule.add_mem _ h_ι_X_pow_in_V' ( Submodule.smul_mem _ a ih ) using 1 ; simp +decide [ pow_succ, mul_assoc ];
        rw [ show ( Polynomial.C a * Polynomial.X ^ n : Polynomial ℂ ) = a • Polynomial.X ^ n by simp +decide [ Polynomial.smul_eq_C_mul ], ι.map_smul ] ; simp +decide [ mul_comm ];
    -- Since ι 1 and ι X are in V', we can show that ι P is in V' for any polynomial P.
    have h_ι_P_in_V' : ∀ P : Polynomial ℂ, ι P ∈ V' ι a := by
      intro P
      induction' P using Polynomial.induction_on' with P Q hP hQ;
      · simpa using Submodule.add_mem _ hP hQ;
      · convert Submodule.smul_mem _ ‹ℂ› ( h_ι_X_pow_in_V' ‹_› ) using 1 ; simp +decide [ ← Polynomial.C_mul_X_pow_eq_monomial ];
        convert ι.map_smul ‹ℂ› ( Polynomial.X ^ ‹_› ) using 1 ; simp +decide [ Polynomial.smul_eq_C_mul ];
    -- Since ι P is in V' for any polynomial P, we can show that V' is equal to H.
    have h_V'_eq_H : V' ι a = ⊤ := by
      refine' eq_top_iff.mpr fun x hx => _;
      -- Since $x$ is in the top subspace, there exists a sequence of polynomials $P_n$ such that $\iota(P_n) \to x$.
      obtain ⟨P_n, hP_n⟩ : ∃ P_n : ℕ → Polynomial ℂ, Filter.Tendsto (fun n => ι (P_n n)) Filter.atTop (nhds x) := by
        have := hι_dense x;
        rw [ mem_closure_iff_seq_limit ] at this;
        exact ⟨ fun n => Classical.choose ( this.choose_spec.1 n ), by simpa only [ Classical.choose_spec ( this.choose_spec.1 _ ) ] using this.choose_spec.2 ⟩;
      exact ( IsClosed.mem_of_tendsto ( show IsClosed ( V' ι a ) from isClosed_closure ) hP_n ) ( Filter.Eventually.of_forall fun n => h_ι_P_in_V' _ );
    simp +decide [ h_V'_eq_H ]

/-
Codimension Dichotomy Theorem: Let H be the closure of polynomials with respect to a Hilbert norm, and a ∈ ℂ. Let V be the closure of polynomials vanishing at a.
1. If a is a Bounded Point Evaluation (BPE), then V is a closed hyperplane and codim(V) = 1.
2. If a is not a BPE, then V is dense in H and codim(V) = 0.
-/
open Polynomial InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

theorem codimension_dichotomy
  (ι : Polynomial ℂ →ₗ[ℂ] H) (hι_dense : DenseRange ι) (hι_inj : Function.Injective ι) (a : ℂ) :
  (is_BPE ι a → Module.rank ℂ ↥(V' ι a)ᗮ = 1) ∧
  (¬ is_BPE ι a → Module.rank ℂ ↥(V' ι a)ᗮ = 0) := by
  constructor
  · exact codimension_one_of_BPE ι hι_dense hι_inj a
  · exact codimension_zero_of_not_BPE ι hι_dense hι_inj a